# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'
name: blazorapp

services:
  blazorapp:
    image: blazorapp
    build:
      context: .
      dockerfile: src/BlazorApp/Server/Dockerfile
    ports:
      - 8080:8080
