x-generator: NSwag v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))
openapi: 3.0.0
info:
  title: BlazorApp
  version: v1
servers:
  - url: https://localhost:7188
paths:
  /api/v1/identity/register:
    post:
      tags:
        - BlazorApp
        - Identity
      operationId: PostApiV1IdentityRegister
      requestBody:
        x-name: registration
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
        x-position: 1
      responses:
        200:
          description: ""
        400:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HttpValidationProblemDetails"
  /api/v1/identity/login:
    post:
      tags:
        - BlazorApp
        - Identity
      operationId: PostApiV1IdentityLogin
      parameters:
        - name: useCookies
          in: query
          schema:
            type: boolean
            nullable: true
          x-position: 2
        - name: useSessionCookies
          in: query
          schema:
            type: boolean
            nullable: true
          x-position: 3
      requestBody:
        x-name: login
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
        x-position: 1
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccessTokenResponse"
  /api/v1/identity/refresh:
    post:
      tags:
        - BlazorApp
        - Identity
      operationId: PostApiV1IdentityRefresh
      requestBody:
        x-name: refreshRequest
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RefreshRequest"
        x-position: 1
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccessTokenResponse"
  /api/v1/identity/confirmEmail:
    get:
      tags:
        - BlazorApp
        - Identity
      operationId: GetApiV1IdentityConfirmEmail
      parameters:
        - name: userId
          in: query
          schema:
            type: string
          x-position: 1
        - name: code
          in: query
          schema:
            type: string
          x-position: 2
        - name: changedEmail
          in: query
          schema:
            type: string
          x-position: 3
      responses:
        200:
          description: ""
  /api/v1/identity/resendConfirmationEmail:
    post:
      tags:
        - BlazorApp
        - Identity
      operationId: PostApiV1IdentityResendConfirmationEmail
      requestBody:
        x-name: resendRequest
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ResendConfirmationEmailRequest"
        x-position: 1
      responses:
        200:
          description: ""
  /api/v1/identity/forgotPassword:
    post:
      tags:
        - BlazorApp
        - Identity
      operationId: PostApiV1IdentityForgotPassword
      requestBody:
        x-name: resetRequest
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ForgotPasswordRequest"
        x-position: 1
      responses:
        200:
          description: ""
        400:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HttpValidationProblemDetails"
  /api/v1/identity/resetPassword:
    post:
      tags:
        - BlazorApp
        - Identity
      operationId: PostApiV1IdentityResetPassword
      requestBody:
        x-name: resetRequest
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ResetPasswordRequest"
        x-position: 1
      responses:
        200:
          description: ""
        400:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HttpValidationProblemDetails"
  /api/v1/identity/manage/2fa:
    post:
      tags:
        - BlazorApp
        - Identity
      operationId: PostApiV1IdentityManage2fa
      requestBody:
        x-name: tfaRequest
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TwoFactorRequest"
        x-position: 1
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TwoFactorResponse"
        400:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HttpValidationProblemDetails"
        404:
          description: ""
      security:
        - JWT: []
  /api/v1/identity/manage/info:
    get:
      tags:
        - BlazorApp
        - Identity
      operationId: GetApiV1IdentityManageInfo
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InfoResponse"
        400:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HttpValidationProblemDetails"
        404:
          description: ""
      security:
        - JWT: []
    post:
      tags:
        - BlazorApp
        - Identity
      operationId: PostApiV1IdentityManageInfo
      requestBody:
        x-name: infoRequest
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InfoRequest"
        x-position: 1
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InfoResponse"
        400:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HttpValidationProblemDetails"
        404:
          description: ""
      security:
        - JWT: []
  /api/v1/requires-auth:
    get:
      tags:
        - BlazorApp
        - BlazorApp
      operationId: BlazorApp_RequiresAuth
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: string
      security:
        - JWT: []
  /api/v1/weatherforecast:
    get:
      tags:
        - BlazorApp
        - WeatherForecast
      operationId: WeatherForecast_GetWeatherForecast
      parameters:
        - name: startDate
          in: query
          required: true
          schema:
            type: string
            format: date
          x-position: 1
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/WeatherForecast"
        400:
          description: ""
  /api/v1/test:
    post:
      tags:
        - BlazorApp
        - BlazorApp
      operationId: BlazorApp_Test
      parameters:
        - name: secretNumber
          in: query
          required: true
          schema:
            type: integer
            format: int32
          x-position: 1
      responses:
        200:
          description: ""
components:
  schemas:
    HttpValidationProblemDetails:
      allOf:
        - $ref: "#/components/schemas/ProblemDetails"
        - type: object
          additionalProperties:
            nullable: true
          properties:
            errors:
              type: object
              additionalProperties:
                type: array
                items:
                  type: string
    ProblemDetails:
      type: object
      additionalProperties:
        nullable: true
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
    RegisterRequest:
      type: object
      additionalProperties: false
      properties:
        email:
          type: string
        password:
          type: string
    AccessTokenResponse:
      type: object
      additionalProperties: false
      properties:
        tokenType:
          type: string
        accessToken:
          type: string
        expiresIn:
          type: integer
          format: int64
        refreshToken:
          type: string
    LoginRequest:
      type: object
      additionalProperties: false
      properties:
        email:
          type: string
        password:
          type: string
        twoFactorCode:
          type: string
          nullable: true
        twoFactorRecoveryCode:
          type: string
          nullable: true
    RefreshRequest:
      type: object
      additionalProperties: false
      properties:
        refreshToken:
          type: string
    ResendConfirmationEmailRequest:
      type: object
      additionalProperties: false
      properties:
        email:
          type: string
    ForgotPasswordRequest:
      type: object
      additionalProperties: false
      properties:
        email:
          type: string
    ResetPasswordRequest:
      type: object
      additionalProperties: false
      properties:
        email:
          type: string
        resetCode:
          type: string
        newPassword:
          type: string
    TwoFactorResponse:
      type: object
      additionalProperties: false
      properties:
        sharedKey:
          type: string
        recoveryCodesLeft:
          type: integer
          format: int32
        recoveryCodes:
          type: array
          nullable: true
          items:
            type: string
        isTwoFactorEnabled:
          type: boolean
        isMachineRemembered:
          type: boolean
    TwoFactorRequest:
      type: object
      additionalProperties: false
      properties:
        enable:
          type: boolean
          nullable: true
        twoFactorCode:
          type: string
          nullable: true
        resetSharedKey:
          type: boolean
        resetRecoveryCodes:
          type: boolean
        forgetMachine:
          type: boolean
    InfoResponse:
      type: object
      additionalProperties: false
      properties:
        email:
          type: string
        isEmailConfirmed:
          type: boolean
        claims:
          type: object
          additionalProperties:
            type: string
    InfoRequest:
      type: object
      additionalProperties: false
      properties:
        newEmail:
          type: string
          nullable: true
        newPassword:
          type: string
          nullable: true
        oldPassword:
          type: string
          nullable: true
    WeatherForecast:
      type: object
      additionalProperties: false
      properties:
        date:
          type: string
          format: date
        temperatureC:
          type: integer
          format: int32
        summary:
          type: string
          nullable: true
        temperatureF:
          type: integer
          format: int32
  securitySchemes:
    JWT:
      type: apiKey
      description: "Type into the textbox: Bearer {your JWT token}."
      name: Authorization
      in: header
